@baseUrl = http://localhost:4000
@xUserId = 3

### Movie by id - fast response
GET {{baseUrl}}/movie/1
x-user-id: {{xUserId}}

### Movie by id - slow response
GET {{baseUrl}}/movie/5
x-user-id: {{xUserId}}

### Movie by id - error response
GET {{baseUrl}}/movie/10
x-user-id: {{xUserId}}

### Movie by id - no user
GET {{baseUrl}}/movie/1

### Movie by id - invalid user
GET {{baseUrl}}/movie/1
x-user-id: 909


### Healthcheck
GET {{baseUrl}}/health
x-user-id: {{xUserId}}